#tc-클라우드프레임워크개발팀/9666: [CloudTrail] 외부 저장소 로그 저장시 무결성 검증 설정 기능 추가 및 퍼브릭 API 노출
TOAST-DOCS/CloudTrail pull request #17
Opened 2023-05-23 06:01 UTC by YunWon123

2023-05-24 02:25 UTC, bgcho98 requested changes

2023-05-24 02:25 UTC, bgcho98 commented on ko/console-guide.md
> +       * **유저ID**의 경우 해당 Object Storage에 권한이 있는 NHN Cloud 유저의 이메일을 입력합니다.
IAM 계정은 id 로 명시가 되어야 합니다.

2023-05-24 02:30 UTC, YunWon123 commented on ko/console-guide.md
> +       * **유저ID**의 경우 해당 Object Storage에 권한이 있는 NHN Cloud 유저의 이메일을 입력합니다.
이 부분 관련해서 확인을 해보았는데요, lncs에서 제공하는 '무결성 검증 등록' API에서, 유저 ID의 경우 현재 이메일 형태만 받을 수 있게 되어 있다고 합니다.
(실제로 IAM 계정으로 테스트해본 결과 500 internal server error가 발생했고 이는 lncs로 API를 요청한 결과로 확인하였습니다.)
따라서 현재는 NHN Cloud 유저의 이메일 주소만 인식 가능한 것으로 판단하였습니다.

2023-05-24 02:56 UTC, bgcho98 approved these changes

2023-05-24 02:56 UTC, bgcho98 commented on ko/console-guide.md
> +       * **유저ID**의 경우 해당 Object Storage에 권한이 있는 NHN Cloud 유저의 이메일을 입력합니다.
헉.. 넵 알겠습니다.

2023-05-24 02:56 UTC, bgcho98 approved these changes

2023-05-24 03:16 UTC, hyunjoo-yi approved these changes
👍

2023-05-24 05:02 UTC, JW-Jason approved these changes
👍

2023-05-31 01:49 UTC, vanillabb commented on ko/console-guide.md
> +    * 3회 이상 업로드에 실패하면 저장된 인증 정보가 비활성화됩니다. **결과 수신**(이메일)에 등록된 메일로 내용이 통보됩니다.
**결과 수신**(이메일)에 -> **결과 수신(이메일)**에

: '결과 수신(이메일)' 까지가 UI 텍스트이므로 전체 볼드 서식 적용합니다.

2023-05-31 01:50 UTC, vanillabb commented on ko/console-guide.md
> +    * 외부 로그 변조 시, **결과 수신**(이메일) 에 등록된 메일로 내용이 통보됩니다.
**결과 수신**(이메일)에 -> **결과 수신(이메일)**에

: '결과 수신(이메일)' 까지가 UI 텍스트이므로 전체 볼드 서식 적용합니다.

2023-05-31 01:55 UTC, vanillabb commented on ko/release-notes.md
> +### 2023. 06. 27
### 2023. 06. 27 -> ### 2023. 06. 27.

날짝 표기 맨 뒤 마침표 추가
(날짜 표기의 마치표는 년, 월, 일을 간략히 표기한 것이므로 생략하지 않고 찍어줍니다.)

2023-05-31 02:15 UTC, YunWon123 commented on ko/release-notes.md
> +### 2023. 06. 27
[7524ff2](https://github.com/TOAST-DOCS/CloudTrail/pull/17/commits/7524ff2b02eeed4eb5ae23983e63aa3a12e4c442) 에 검수 주신 의견 반영하였습니다.

2023-05-31 02:15 UTC, YunWon123 commented on ko/console-guide.md
> +    * 외부 로그 변조 시, **결과 수신**(이메일) 에 등록된 메일로 내용이 통보됩니다.
[7524ff2](https://github.com/TOAST-DOCS/CloudTrail/pull/17/commits/7524ff2b02eeed4eb5ae23983e63aa3a12e4c442) 에 검수 주신 의견 반영하였습니다.

2023-05-31 02:15 UTC, YunWon123 commented on ko/console-guide.md
> +    * 3회 이상 업로드에 실패하면 저장된 인증 정보가 비활성화됩니다. **결과 수신**(이메일)에 등록된 메일로 내용이 통보됩니다.
[7524ff2](https://github.com/TOAST-DOCS/CloudTrail/pull/17/commits/7524ff2b02eeed4eb5ae23983e63aa3a12e4c442) 에 검수 주신 의견 반영하였습니다.

2023-06-14 06:47 UTC, merged